Added play status
LINK1733/game-tracker pull request #10
Opened 2021-09-13 17:04 UTC by LINK1733

Added a play status to each game. There is a dropdown on the Game Page that you pick what the game's status is. By default it is planning to play. I also have it hide the option for whatever the current play status is so that way there isn't the option to change it to whatever it currently is set to.

Made the gamePlayStatus it's own component so it won't clutter the gamePage component file.

Also added next to the props of the controller for game.js since I realized it was missing to it would error out if those functions ever got an actual error.

![image](https://user-images.githubusercontent.com/10948163/133126338-1c729311-663b-4fb2-ab8a-718dc654a8ae.png)
![image](https://user-images.githubusercontent.com/10948163/133126361-36fa4602-976f-4f97-b2fd-ad072dbc938a.png)
![image](https://user-images.githubusercontent.com/10948163/133126375-27b6b9df-9d7d-4bae-ad1c-9461944c12a2.png)

2021-09-13 23:00 UTC, sheodox requested changes
This could use a lot of cleanup. You have three formats for your statuses, camel case in the browser, pascal case in the database enum, and title case for the actual display text. I think  you could remove the camel case, as you go through a lot of effort converting back and forth between camel case to pascal case (in your express controller for the update route) and from pascal case to camel case (in the browser determining which status text to show).

There's really no need for two casing formats. It's especially weird when you think of it because the server only sends PascalCase, but only accepts `camelCase` updates, it should be consistent. If the database only accepts the PascalCase enum names then you should just stick with that everywhere.

Additionally I think you should be able to simplify `gamePlayStatus.js` a ton if you make an array of statuses and did something like this:

```javascript
const statuses = [{
	id: 'PlanToPlay',
	text: 'Plan to Play',
}, {
	id: 'Dropped',
	text: 'Dropped',
}, {
	id: 'Completed',
	text: 'Completed',
}, {
	id: 'Hold',
	text: 'On Hold',
}];

// ...

return (
	<div>
		<ul>
			{statuses
				.filter(status => status.id !== playStatus)
				.map(status => {
					return <li>
						<button
							onClick={() => changePlayStatus(status.id}
						>{status.text}</button>
					</li>
				})
			}
		</ul>
	</div>
);
```

2021-09-14 03:31 UTC, LINK1733 commented on prisma/migrations/20210913001502_added_enum_for_play_status/migration.sql
> +CREATE TYPE "Progress" AS ENUM ('PlanToPlay', 'Dropped', 'Completed', 'Playing');
We discussed this over discord so I will mark this as resolved. You had mentioned you didn't notice the second migration.

2021-09-14 03:32 UTC, LINK1733 commented on src/server/controllers/game.js
> +module.exports.showGame = catchAsync(async (req, res, next) => {
Nice. Look forward to taking a dive into that later.

2021-09-14 03:32 UTC, LINK1733 commented on src/server/controllers/game.js
> +			},
Mentioned this on discord but will say it again here. It is necessary due to me sending the game object back in the same function so it needs this so it has the game name and photo.

2021-09-14 03:33 UTC, LINK1733 commented on src/static/components/gamePlayStatus.js
> +				</li>
Gotcha. They're buttons now since I'm doing something similar to what you have above with the status array and mapping over that.

2021-09-14 03:59 UTC, LINK1733 commented on src/static/components/gamePlayStatus.js
> +		elements.playing.style.display = 'flex';
Ended up removing the need for this by using the filter stuff for the statuses array.

2021-09-14 04:04 UTC, LINK1733 commented
Ok I believe this should all be resolved now?

2021-09-14 23:24 UTC, sheodox commented on src/static/components/gamePage.js
> +				key={gamePageInfo.id}
Did you actually need a key here? Generally you don't need a key unless you've got an array of items.

2021-09-14 23:24 UTC, sheodox commented on src/static/components/gamePlayStatus.js
> +	const currentStatus = filteredStatus.map((filtered) => filtered.text);
Here you're just filtering down to a single item length array, then getting an array of the text of that item. This is a really roundabout way to do it! And you don't really even want the array in the end. Id do something like:

```javascript
const currentStatus = statuses.find(status => status.id === playStatus).text;
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

2021-09-14 23:26 UTC, sheodox commented on src/static/components/gamePlayStatus.js
> +									className="btn btn-link col-12 dropdownLink"
Would removing `btn-link` make these look like what you want? What about doing something like this from the bootstrap docs? https://getbootstrap.com/docs/5.1/components/dropdowns/#single-button

2021-09-15 02:54 UTC, LINK1733 commented on src/static/components/gamePlayStatus.js
> +									className="btn btn-link col-12 dropdownLink"
Without the btn-link they show as buttons within the li's. I had it like in that example earlier just without the a tags cause it was putting the # in the url and I wasn't sure if it should be doing that and you said I should make them buttons instead.

2021-09-15 22:10 UTC, sheodox approved these changes

2021-09-16 12:22 UTC, merged